---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: ingress - metadata - name
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
  - ../_values/ingress_main_default_hosts.yaml
  - ../_values/service_main_default.yaml
tests:
  - it: name defaults to chart fullName
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: release-name
          any: true

  - it: forceRename
    set:
      ingress.main.forceRename: forceRename
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: forcerename
          any: true

  - it: forceRename with template
    set:
      ingress.main.forceRename: "{{ .Chart.Name }}"
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: common-test
          any: true

  - it: prefix
    set:
      ingress.main.prefix: prefix
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: prefix-release-name
          any: true

  - it: prefix with template
    set:
      ingress.main.prefix: "{{ .Chart.Name }}"
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: common-test-release-name
          any: true

  - it: suffix
    set:
      ingress.main.suffix: suffix
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: release-name-suffix
          any: true

  - it: suffix with template
    set:
      ingress.main.suffix: "{{ .Chart.Name }}"
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: release-name-common-test
          any: true

  - it: both prefix and suffix
    set:
      ingress.main.prefix: prefix
      ingress.main.suffix: suffix
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: prefix-release-name-suffix
          any: true

  - it: prefix, suffix and forceRename (illegal combination)
    set:
      ingress.main.forceRename: forceRename
      ingress.main.prefix: prefix
      ingress.main.suffix: suffix
    asserts:
      - failedTemplate:
          errorPattern: "values don't meet the specifications of the schema"

  - it: multiple items
    set:
      ingress:
        second:
          hosts:
            - host: "chart-example.local"
              paths:
                - path: /
                  service:
                    name: RELEASE-NAME
                    port: 8081
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: release-name-second
          any: true

  - it: multiple items with prefix
    set:
      ingress:
        second:
          prefix: prefix
          hosts:
            - host: "chart-example.local"
              paths:
                - path: /
                  service:
                    name: RELEASE-NAME
                    port: 8081
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: prefix-release-name-second
          any: true

  - it: multiple items with suffix
    set:
      ingress:
        second:
          suffix: suffix
          hosts:
            - host: "chart-example.local"
              paths:
                - path: /
                  service:
                    name: RELEASE-NAME
                    port: 8081
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: release-name-second-suffix
          any: true

  - it: multiple items with prefix and suffix
    set:
      ingress:
        second:
          prefix: prefix
          suffix: suffix
          hosts:
            - host: "chart-example.local"
              paths:
                - path: /
                  service:
                    name: RELEASE-NAME
                    port: 8081
    asserts:
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Ingress
          apiVersion: networking.k8s.io/v1
          name: prefix-release-name-second-suffix
          any: true

  - it: multiple items with prefix, suffix and forceRename (illegal combination)
    set:
      ingress:
        second:
          forceRename: forceRename
          prefix: prefix
          suffix: suffix
          hosts:
            - host: "chart-example.local"
              paths:
                - path: /
                  service:
                    name: RELEASE-NAME
                    port: 8081
    asserts:
      - failedTemplate:
          errorPattern: "values don't meet the specifications of the schema"
