---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: serviceAccount - metadata - name
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  serviceAccount.main: {}
tests:
  - it: name defaults to chart fullName
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name
          any: true

  - it: forceRename
    set:
      serviceAccount.main.forceRename: forceRename
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: forcerename
          any: true

  - it: forceRename with template
    set:
      serviceAccount.main.forceRename: "{{ .Chart.Name }}"
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: common-test
          any: true

  - it: prefix
    set:
      serviceAccount.main.prefix: prefix
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: prefix-release-name
          any: true

  - it: prefix with template
    set:
      serviceAccount.main.prefix: "{{ .Chart.Name }}"
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: common-test-release-name
          any: true

  - it: suffix
    set:
      serviceAccount.main.suffix: suffix
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name-suffix
          any: true

  - it: suffix with template
    set:
      serviceAccount.main.suffix: "{{ .Chart.Name }}"
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name-common-test
          any: true

  - it: both prefix and suffix
    set:
      serviceAccount.main.prefix: prefix
      serviceAccount.main.suffix: suffix
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: prefix-release-name-suffix
          any: true

  - it: prefix, suffix and forceRename (illegal combination)
    set:
      serviceAccount.main.forceRename: forceRename
      serviceAccount.main.prefix: prefix
      serviceAccount.main.suffix: suffix
    asserts:
      - failedTemplate:
          errorPattern: "values don't meet the specifications of the schema"

  - it: multiple items
    set:
      serviceAccount.second: {}
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name-second
          any: true

  - it: multiple items with prefix
    set:
      serviceAccount.second:
        prefix: prefix
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: prefix-release-name-second
          any: true

  - it: multiple items with suffix
    set:
      serviceAccount.second:
        suffix: suffix
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name-second-suffix
          any: true

  - it: multiple items with prefix and suffix
    set:
      serviceAccount.second:
        prefix: prefix
        suffix: suffix
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: prefix-release-name-second-suffix
          any: true

  - it: multiple items with prefix, suffix and forceRename (illegal combination)
    set:
      serviceAccount.second:
        forceRename: forceRename
        prefix: prefix
        suffix: suffix
    asserts:
      - failedTemplate:
          errorPattern: "values don't meet the specifications of the schema"
