---
apiVersion: v2
appVersion: 1.0.3
description: Webhook for Prometheus Alertmanager to listen for notifications and pushes them to Discord channel
name: alertmanager-discord
version: 1.6.0
kubeVersion: '>=1.16.0-0'
keywords:
  - alertmanager
  - discord
  - alerting
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/alertmanager-discord
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
sources:
  - https://github.com/rogerrum/alertmanager-discord
  - https://hub.docker.com/r/rogerrum/alertmanager-discord
maintainers:
  - name: j0sh3rs
    email: github@beholdthehurricane.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.1.0
