apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "matrix.fullname" . }}-media-store
  labels:
{{ include "matrix.labels" . | indent 4}}
{{ include "matrix.synapse.labels" . | indent 4}}
spec:
  {{- if .Values.volumes.media.storageClass }}
  storageClassName: {{ .Values.volumes.media.storageClass }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.media.capacity }}
