---
# Project information
site_name: bjw-s Helm Charts
site_url: https://bjw-s.github.io/helm-charts/
site_author: bjw-s

# Repository
repo_name: bjw-s/helm-charts
repo_url: https://github.com/bjw-s/helm-charts

# Configuration
docs_dir: ../../docs
site_dir: ../../site

theme:
  name: material
  custom_dir: ../../docs/overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggest
  palette:
    scheme: slate
    primary: black
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/kubernetes

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3

# Page tree
nav:
  - index.md
  - Common Library:
      - common-library/index.md
      - Storage:
          - Permissions: common-library/storage/permissions.md
          - Global options: common-library/storage/globalOptions.md
          - Types-specific options:
              - configMap: common-library/storage/types/configmap.md
              - Custom: common-library/storage/types/custom.md
              - emptyDir: common-library/storage/types/emptyDir.md
              - hostPath: common-library/storage/types/hostPath.md
              - NFS share: common-library/storage/types/nfs-share.md
              - persistentVolumeClaim: common-library/storage/types/persistentVolumeClaim.md
              - Secret: common-library/storage/types/secret.md
  - App Template:
      - app-template/index.md
      - How To...:
          - app-template/howto/index.md
          - Helm templates: app-template/howto/helm-templates.md
          - Multiple subPaths for 1 volume: app-template/howto/multiple-subpath.md
          - Multiple services with 1 or more controllers: app-template/howto/multiple-services.md
      - Examples:
          - app-template/examples/index.md
          - Home-Assistant with code-server: app-template/examples/home-assistant-codeserver.md
          - qBittorrent with Gluetun: app-template/examples/qbittorrent-gluetun.md
