---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: job - metadata - name
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  controllers.main.type: job
tests:
  - it: name defaults to chart fullName
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: release-name
          any: true

  - it: forceRename
    set:
      controllers.main.forceRename: forceRename
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: forcerename
          any: true

  - it: forceRename with template
    set:
      controllers.main.forceRename: "{{ .Chart.Name }}"
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: common-test
          any: true

  - it: prefix
    set:
      controllers.main.prefix: prefix
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: prefix-release-name
          any: true

  - it: prefix with template
    set:
      controllers.main.prefix: "{{ .Chart.Name }}-prefix"
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: common-test-prefix-release-name
          any: true

  - it: suffix
    set:
      controllers.main.suffix: suffix
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: release-name-suffix
          any: true

  - it: suffix with template
    set:
      controllers.main.suffix: "{{ .Chart.Name }}-suffix"
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: release-name-common-test-suffix
          any: true

  - it: both prefix and suffix
    set:
      controllers.main.prefix: prefix
      controllers.main.suffix: suffix
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: prefix-release-name-suffix
          any: true

  - it: prefix, suffix and forceRename (illegal combination)
    set:
      controllers.main.forceRename: forceRename
      controllers.main.prefix: prefix
      controllers.main.suffix: suffix
    asserts:
      - failedTemplate:
          errorPattern: "values don't meet the specifications of the schema"

  - it: multiple items
    set:
      controllers:
        second:
          type: job
          containers:
            main:
              image:
                repository: ghcr.io/mendhak/http-https-echo
                tag: 31
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: release-name-second
          any: true

  - it: multiple items with prefix
    set:
      controllers:
        second:
          type: job
          prefix: prefix
          containers:
            main:
              image:
                repository: ghcr.io/mendhak/http-https-echo
                tag: 31
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: prefix-release-name-second
          any: true

  - it: multiple items with suffix
    set:
      controllers:
        second:
          type: job
          suffix: suffix
          containers:
            main:
              image:
                repository: ghcr.io/mendhak/http-https-echo
                tag: 31
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: release-name-second-suffix
          any: true

  - it: multiple items with prefix and suffix
    set:
      controllers:
        second:
          type: job
          prefix: prefix
          suffix: suffix
          containers:
            main:
              image:
                repository: ghcr.io/mendhak/http-https-echo
                tag: 31
    asserts:
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: prefix-release-name-second-suffix
          any: true

  - it: multiple items with prefix, suffix and forceRename (illegal combination)
    set:
      controllers:
        second:
          type: job
          forceRename: forceRename
          prefix: prefix
          suffix: suffix
          containers:
            main:
              image:
                repository: ghcr.io/mendhak/http-https-echo
                tag: 31
    asserts:
      - failedTemplate:
          errorPattern: "values don't meet the specifications of the schema"
