---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: container restartPolicy
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    asserts:
      - documentIndex: 0
        isKind:
          of: Deployment
      - documentIndex: 0
        notExists:
          path: spec.template.spec.containers[0].restartPolicy

  - it: custom restartPolicy should pass
    set:
      controllers.main.containers:
        main:
          restartPolicy: Always

    asserts:
      - documentIndex: 0
        isKind:
          of: Deployment
      - documentIndex: 0
        equal:
          path: spec.template.spec.containers[0].restartPolicy
          value: Always
