---
# yaml-language-server: $schema=../../common/values.schema.json
controllers:
  main:
    type: cronjob
    cronjob:
      timeZone: UTC
      schedule: "*/20 * * * *"
    containers:
      main:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 31
          pullPolicy: IfNotPresent

configMaps:
  config:
    enabled: true
    data:
      test: value 1
