---
apiVersion: v2
appVersion: 1.25.2
description: Vaultwarden is a Bitwarden compatable server in Rust
name: vaultwarden
version: 5.4.0
kubeVersion: ">=1.16.0-0"
keywords:
  - Vaultwarden
  - bitwardenrs
home: "https://github.com/k8s-at-home/charts/tree/master/charts/stable/vaultwarden"
icon: "https://sesoodan.sirv.com/bitwarden_rs.png"
sources:
  - https://github.com/dani-garcia/vaultwarden
maintainers:
  - name: j0sh3rs
    email: j0sh3rs@pm.me
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: mariadb
    version: 11.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 11.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
