---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: secret - metadata - name
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  secrets.main:
    stringData:
      test: test
tests:
  - it: name defaults to chart fullName
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: release-name
          any: true

  - it: forceRename
    set:
      secrets.main.forceRename: forceRename
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: forcerename
          any: true

  - it: forceRename with template
    set:
      secrets.main.forceRename: "{{ .Chart.Name }}"
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: common-test
          any: true

  - it: prefix
    set:
      secrets.main.prefix: prefix
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: prefix-release-name
          any: true

  - it: prefix with template
    set:
      secrets.main.prefix: "{{ .Chart.Name }}"
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: common-test-release-name
          any: true

  - it: suffix
    set:
      secrets.main.suffix: suffix
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: release-name-suffix
          any: true

  - it: suffix with template
    set:
      secrets.main.suffix: "{{ .Chart.Name }}"
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: release-name-common-test
          any: true

  - it: both prefix and suffix
    set:
      secrets.main.prefix: prefix
      secrets.main.suffix: suffix
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: prefix-release-name-suffix
          any: true

  - it: prefix, suffix and forceRename (illegal combination)
    set:
      secrets.main.forceRename: forceRename
      secrets.main.prefix: prefix
      secrets.main.suffix: suffix
    asserts:
      - failedTemplate:
          errorPattern: "values don't meet the specifications of the schema"

  - it: multiple items
    set:
      secrets.second:
        stringData:
          test: test
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: release-name-second
          any: true

  - it: multiple items with prefix
    set:
      secrets.second:
        prefix: prefix
        stringData:
          test: test
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: prefix-release-name-second
          any: true

  - it: multiple items with suffix
    set:
      secrets.second:
        suffix: suffix
        stringData:
          test: test
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: release-name-second-suffix
          any: true

  - it: multiple items with prefix and suffix
    set:
      secrets.second:
        prefix: prefix
        suffix: suffix
        stringData:
          test: test
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: prefix-release-name-second-suffix
          any: true

  - it: multiple items with prefix, suffix and forceRename (illegal combination)
    set:
      secrets.second:
        forceRename: forceRename
        prefix: prefix
        suffix: suffix
        stringData:
          test: test
    asserts:
      - failedTemplate:
          errorPattern: "values don't meet the specifications of the schema"
