# ---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
# TODO: Move this to the pod metadata tests
# suite: secret Pod metadata
# templates:
#   - common.yaml
# values:
#   - ../_values/controllers_main_default_container.yaml
# tests:
#   - it: default metadata should pass
#     set:
#       secrets:
#         secret_1:
#           stringData:
#             test: value 1
#         secret_2: # default enabled
#           stringData:
#             test_1: value 1
#             test_2: value 2
#         test_not_in_checksum:
#           includeInChecksum: false
#           stringData:
#             test: value 1
#         test_disabled:
#           enabled: false
#           stringData:
#             test: value 1
#     asserts:
#       - documentIndex: &ControllerDoc 0
#         isKind:
#           of: Deployment
#       - documentIndex: *ControllerDoc
#         equal:
#           path: spec.template.metadata.annotations
#           value:
#             checksum/secrets: cd4e5076088172611ca1c43c659a275232d9eeb887acc20575ac141038b9aacb
