name: "Charts: Release"

concurrency: helm-release

on:
  workflow_dispatch:
    inputs:
      charts:
        description: >
          Charts to release. Comma-separated string.
          Defaults to releasing everything.
        default: ""
        required: false

  push:
    branches:
      - main
    paths:
      - "charts/**"

env:
  HELM_VERSION: 3.9.2

jobs:
  prepare:
    name: Prepare data required for release
    runs-on: ubuntu-22.04
    outputs:
      charts-to-release: ${{ steps.collect-charts.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect charts to release
        uses: bjw-s/helm-charts-actions/collect-charts@main
        id: collect-charts
        with:
          repoConfigFile: ./.ci/repo-config.yaml
          overrideCharts: "[${{ inputs.charts }}]"

  release-github-pages:
    name: Release Charts to GitHub pages
    uses: ./.github/workflows/charts-release-ghpages.yaml
    needs:
      - prepare
    with:
      charts: "${{ needs.prepare.outputs.charts-to-release }}"
    secrets: inherit
