name: "Pull Request: Validate"

on:
  pull_request:
    branches:
      - main
      - development
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  pr-metadata:
    uses: bjw-s/helm-charts/.github/workflows/pr-metadata.yaml@main

  pre-commit-check:
    uses: bjw-s/helm-charts/.github/workflows/pre-commit-check.yaml@main
    needs:
      - pr-metadata
    with:
      modifiedFiles: ${{ needs.pr-metadata.outputs.addedOrModifiedFiles }}

  charts-lint:
    uses: bjw-s/helm-charts/.github/workflows/charts-lint.yaml@main
    needs:
      - pr-metadata
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToLint: ${{ needs.pr-metadata.outputs.chartsToLint }}
      isRenovatePR: ${{ needs.pr-metadata.outputs.isRenovatePR }}

  charts-test:
    uses: bjw-s/helm-charts/.github/workflows/charts-test.yaml@main
    needs:
      - pr-metadata
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToTest: ${{ needs.pr-metadata.outputs.chartsToInstall }}

  library-charts-test:
    uses: bjw-s/helm-charts/.github/workflows/charts-test.yaml@main
    needs:
      - pr-metadata
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToTest: |-
        ${{
          (
            contains(fromJSON(needs.pr-metadata.outputs.addedOrModifiedCharts), 'library/common') &&
            '["other/kah-common-chart"]'
          ) || '[]'
        }}
      overrideDeps: |-
        [
          {"name": "common", "repository": "file://../../library/common", "version": "*"}
        ]
