name: "Pull Request: Validate"

on:
  pull_request:
    branches:
      - main
      - development
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  pr-metadata:
    uses: ./.github/workflows/pr-metadata.yaml

  pre-commit-check:
    uses: ./.github/workflows/pre-commit-check.yaml
    needs:
      - pr-metadata
    with:
      modifiedFiles: ${{ needs.pr-metadata.outputs.addedOrModifiedFiles }}

  charts-lint:
    uses: ./.github/workflows/charts-lint.yaml
    needs:
      - pr-metadata
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToLint: ${{ needs.pr-metadata.outputs.chartsToLint }}
      isRenovatePR: ${{ needs.pr-metadata.outputs.isRenovatePR }}
      overrideDeps: |-
        ${{
           (
             needs.pr-metadata.outputs.commonLibraryUpdated &&
            '[{"name": "common", "repository": "file://../../library/common", "version": "*"}]'
           ) || '[]'
         }}

  charts-test:
    uses: ./.github/workflows/charts-test.yaml
    needs:
      - pr-metadata
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToTest: |-
        ${{
           (
             (needs.pr-metadata.outputs.commonLibraryUpdated=='true') &&
             '["other/app-template"]'
           ) || needs.pr-metadata.outputs.chartsToInstall
         }}
      overrideDeps: |-
        ${{
           (
             needs.pr-metadata.outputs.commonLibraryUpdated &&
            '[{"name": "common", "repository": "file://../../library/common", "version": "*"}]'
           ) || '[]'
         }}
