name: "Charts: Create git tag"

on:
  workflow_call:
    inputs:
      charts:
        description: >
          Json encoded list of Helm charts to release.
          Defaults to releasing everything.
        default: "[]"
        required: false
        type: string
    secrets:
      BJWS_APP_ID:
        required: true
      BJWS_APP_PRIVATE_KEY:
        required: true

env:
  CHARTS_SRC_DIR: "charts"

jobs:
  tag-charts:
    name: Tag charts
    runs-on: ubuntu-22.04
    steps:
      - name: "Generate Short Lived OAuth App Token (ghs_*)"
        uses: actions/create-github-app-token@v1.9.3
        id: app-token
        with:
          app-id: "${{ secrets.BJWS_APP_ID }}"
          private-key: "${{ secrets.BJWS_APP_PRIVATE_KEY }}"

      - name: Checkout chart sources
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Create git tag for charts
        shell: bash
        run: |
          CHARTS=( $(yq --null-input e '${{ inputs.charts }}[]' ) )

          for CHART in "${CHARTS[@]}" ; do
            mapfile -t CHART_PATH_PARTS < <(echo "$CHART" | tr '/' '\n')
            CHART_TYPE=${CHART_PATH_PARTS[0]}
            CHART_NAME=${CHART_PATH_PARTS[1]}
            CHART_VERSION=$(yq e '.version' ${{ env.CHARTS_SRC_DIR }}/${CHART}/Chart.yaml)

            git tag --force "${CHART_NAME}-${CHART_VERSION}"
          done

          git push --tags --force
